# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lash < Formula
  desc ""
  homepage ""
  version "0.4.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lacymorrow/lash/releases/download/v0.4.6/lash_0.4.6_Darwin_x86_64.tar.gz"
      sha256 "0f109b0a6ba554f93f6a337f619a41c67c7653cdee6f915dc029b804e3ed6b91"

      def install
        bin.install "lash"
        bash_completion.install "completions/lash.bash" => "lash"
        zsh_completion.install "completions/lash.zsh" => "_lash"
        fish_completion.install "completions/lash.fish"
        man1.install "manpages/lash.1.gz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lacymorrow/lash/releases/download/v0.4.6/lash_0.4.6_Darwin_arm64.tar.gz"
      sha256 "28688a6af8f84f11264fab50ef9e5802e94f5db9f93a6b19848181e0e35465b2"

      def install
        bin.install "lash"
        bash_completion.install "completions/lash.bash" => "lash"
        zsh_completion.install "completions/lash.zsh" => "_lash"
        fish_completion.install "completions/lash.fish"
        man1.install "manpages/lash.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/lacymorrow/lash/releases/download/v0.4.6/lash_0.4.6_Linux_x86_64.tar.gz"
      sha256 "e00742604a6b6342b774962372eed8e07b7b83bcf220ee2e5f612f78c43f1342"
      def install
        bin.install "lash"
        bash_completion.install "completions/lash.bash" => "lash"
        zsh_completion.install "completions/lash.zsh" => "_lash"
        fish_completion.install "completions/lash.fish"
        man1.install "manpages/lash.1.gz"
      end
    end
    if Hardware::CPU.arm? and !Hardware::CPU.is_64_bit?
      url "https://github.com/lacymorrow/lash/releases/download/v0.4.6/lash_0.4.6_Linux_armv7.tar.gz"
      sha256 "1457c3633125897e773c1592caeacf2583599a6e791654388f16ea20ab4faa3a"
      def install
        bin.install "lash"
        bash_completion.install "completions/lash.bash" => "lash"
        zsh_completion.install "completions/lash.zsh" => "_lash"
        fish_completion.install "completions/lash.fish"
        man1.install "manpages/lash.1.gz"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/lacymorrow/lash/releases/download/v0.4.6/lash_0.4.6_Linux_arm64.tar.gz"
      sha256 "232606627b8d0318c9457033c34394e5757aedf75940f6be77d972d516da7273"
      def install
        bin.install "lash"
        bash_completion.install "completions/lash.bash" => "lash"
        zsh_completion.install "completions/lash.zsh" => "_lash"
        fish_completion.install "completions/lash.fish"
        man1.install "manpages/lash.1.gz"
      end
    end
  end
end
