# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lash < Formula
  desc ""
  homepage ""
  version "0.4.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lacymorrow/lash/releases/download/v0.4.6/lash_0.4.6_Darwin_x86_64.tar.gz"
      sha256 "0781ddcdb0381e6ce27ef707f3b9fe70733b34d1715ee1276d48131662773b72"

      def install
        bin.install "lash"
        bash_completion.install "completions/lash.bash" => "lash"
        zsh_completion.install "completions/lash.zsh" => "_lash"
        fish_completion.install "completions/lash.fish"
        man1.install "manpages/lash.1.gz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lacymorrow/lash/releases/download/v0.4.6/lash_0.4.6_Darwin_arm64.tar.gz"
      sha256 "d92d2d637b8b2cfa08662d74177045eabd709036c5ea964dea517af2226f918e"

      def install
        bin.install "lash"
        bash_completion.install "completions/lash.bash" => "lash"
        zsh_completion.install "completions/lash.zsh" => "_lash"
        fish_completion.install "completions/lash.fish"
        man1.install "manpages/lash.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/lacymorrow/lash/releases/download/v0.4.6/lash_0.4.6_Linux_x86_64.tar.gz"
      sha256 "555e06f9e2b1043486d1eb0d994416d5baccb83c0536c7667c4e27fd1d710f86"
      def install
        bin.install "lash"
        bash_completion.install "completions/lash.bash" => "lash"
        zsh_completion.install "completions/lash.zsh" => "_lash"
        fish_completion.install "completions/lash.fish"
        man1.install "manpages/lash.1.gz"
      end
    end
    if Hardware::CPU.arm? and !Hardware::CPU.is_64_bit?
      url "https://github.com/lacymorrow/lash/releases/download/v0.4.6/lash_0.4.6_Linux_armv7.tar.gz"
      sha256 "56eb29d353956f91c44973d765efbc1b82c4348b8268f133721a0770944f0e7b"
      def install
        bin.install "lash"
        bash_completion.install "completions/lash.bash" => "lash"
        zsh_completion.install "completions/lash.zsh" => "_lash"
        fish_completion.install "completions/lash.fish"
        man1.install "manpages/lash.1.gz"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/lacymorrow/lash/releases/download/v0.4.6/lash_0.4.6_Linux_arm64.tar.gz"
      sha256 "0d3d8d95641dc462d762dd0af43260cc8326fe17a82dfc0c7972c029394d3c26"
      def install
        bin.install "lash"
        bash_completion.install "completions/lash.bash" => "lash"
        zsh_completion.install "completions/lash.zsh" => "_lash"
        fish_completion.install "completions/lash.fish"
        man1.install "manpages/lash.1.gz"
      end
    end
  end
end
