# typed: false
# frozen_string_literal: true

# Generated by publish-lash.ts
class Lash < Formula
  desc "The AI coding agent built for the terminal."
  homepage "https://github.com/lacymorrow/lash"
  version "0.6.12"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lacymorrow/lash/releases/download/v0.6.12/lash-darwin-x64.tar.gz"
      sha256 "2c4fb3bca92f320d347ddc4dd31e16e36031583b4497eeafc8466118a19e9564"

      def install
        bin.install "lash"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lacymorrow/lash/releases/download/v0.6.12/lash-darwin-arm64.tar.gz"
      sha256 "b279344e9df305238c623b09812ae7dcc22adc2561912e11a58fa9ee9ebfe3f1"

      def install
        bin.install "lash"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/lacymorrow/lash/releases/download/v0.6.12/lash-linux-x64.tar.gz"
      sha256 "a711bb982d63631a7e64968b3df17b7da94fef02166d223ed41c38928386aa63"
      def install
        bin.install "lash"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/lacymorrow/lash/releases/download/v0.6.12/lash-linux-arm64.tar.gz"
      sha256 "f7fed4be2a75ec3172c6201926e65949a4af699a85eedfc8f233af6c71cad798"
      def install
        bin.install "lash"
      end
    end
  end
end
