# typed: false
# frozen_string_literal: true

# Generated by publish-lash.ts
class Lash < Formula
  desc "The AI coding agent built for the terminal."
  homepage "https://github.com/lacymorrow/lash"
  version "1.0.7"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lacymorrow/lash/releases/download/v1.0.7/lash-cli-darwin-x64.zip"
      sha256 "48b6577829dcff24149d7153463505502e65c3c3f7357d56de3ad20bf5d891c1"

      def install
        bin.install "lash"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lacymorrow/lash/releases/download/v1.0.7/lash-cli-darwin-arm64.zip"
      sha256 "879ce5ae0f7fb2ca4d5a6ca4726efd406b266fd38d1e7d82945055f116f8afd1"

      def install
        bin.install "lash"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/lacymorrow/lash/releases/download/v1.0.7/lash-cli-linux-x64.zip"
      sha256 "dbc457c58a62c99227ced6c6b4f3a7457503486a508443f8c9ef955545d27ba3"
      def install
        bin.install "lash"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/lacymorrow/lash/releases/download/v1.0.7/lash-cli-linux-arm64.zip"
      sha256 "6b70d63e49fd03e787f39acc2176ca240c804df5056f42a2171058e1e23bbb28"
      def install
        bin.install "lash"
      end
    end
  end
end
