# typed: false
# frozen_string_literal: true

# Generated by publish-lash.ts
class Lash < Formula
  desc "The AI coding agent built for the terminal."
  homepage "https://github.com/lacymorrow/lash"
  version "0.6.12"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lacymorrow/lash/releases/download/v0.6.12/lash-darwin-x64.tar.gz"
      sha256 :no_check

      def install
        bin.install "lash"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lacymorrow/lash/releases/download/v0.6.12/lash-darwin-arm64.tar.gz"
      sha256 :no_check

      def install
        bin.install "lash"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/lacymorrow/lash/releases/download/v0.6.12/lash-linux-x64.tar.gz"
      sha256 :no_check
      def install
        bin.install "lash"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/lacymorrow/lash/releases/download/v0.6.12/lash-linux-arm64.tar.gz"
      sha256 :no_check
      def install
        bin.install "lash"
      end
    end
  end
end
